import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from "./topnav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home - Jasmine Draycott",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={inter.className}>
        <div className="pageWrapper">
          <TopNav />
          {children}
        </div>
      </body>
    </html>
  );
}
